### ISSUE TITLE
Spamming the 'play x sec' button plays 2x of the playback

### ISSUE THREAD

**Issue by Satanarious** [theRealPadster/name-that-tune#15]
Spamming the 'play x sec' button plays more than x sec sometimes 2x sec. Depends on how long you spam.

I would suggest disabling the play x sec button when music is playing

**Comment by theRealPadster** [comment]
I'd like to make it so that if you click while it's currently playing, it will start over. But the event listeners are being a major pain. I tested adding an AudioManager class (branch [here](https://github.com/theRealPadster/spurdle/tree/audiomanager)) with a single persistent listener to work around this, and now I'm noticing that if you spam the button, it moves the progress bar back to the beginning, but the audio doesn't always reset. So my "is it done" check, which uses `Spicetify.Player.getProgressPercent()` fails because `Spicetify.Player.getProgressPercent()` is actually giving me the wrong value. Quite the conundrum.

**Comment by theRealPadster** [comment]
The AudioManager seems to work, since it it ever gets past the specified end time, it jumps back to the beginning.
