### ISSUE TITLE
support to arabic and hebrew song titles

### ISSUE THREAD

**Issue by ShaleveHakime** [theRealPadster/name-that-tune#72]
### 📝 Provide a description of the new feature

when i want to guess song with arabic or hebrew title it tells me its wrong even though im right, i think it may be complicated to do that but if you can it will be amazing

### ➕ Additional Information

![image](https://github.com/theRealPadster/name-that-tune/assets/136990507/b4c07c38-14b4-438d-bb46-17890df652d3)
![image](https://github.com/theRealPadster/name-that-tune/assets/136990507/46bad011-f3a2-47bf-8f19-3fe8c8ebdc60)

**Comment by theRealPadster** [comment]
This would be because of the normalization regex it runs on the input string. I don't know enough about Arabic or Hebrew to know what to add so that their alphabets are allowed. 

```ts
// Remove everything (including spaces) that is not a number, letter, Cyrylic alphabet, Polish alphabet
cleaned = cleaned.replace(/[^\wа-яА-ЯіїІЇ\dąćęłńóśźż\d]/g, '');
```
https://github.com/theRealPadster/name-that-tune/blob/cf650699fc1aec52223e1b1f80848d4d8572c69d/src/logic.ts#L32C1-L33C1

**Comment by theRealPadster** [comment]
I asked github copilot to add support and it came out with this:

> Sure, you can add Arabic and Hebrew letters to your regular expression. Arabic letters range from \u0621 to \u064A and Hebrew letters range from \u05D0 to \u05EA. Here is how you can modify your code:

```ts
// Remove everything (including spaces) that is not a number, letter, Cyrylic alphabet, Polish alphabet, Arabic and Hebrew letters
cleaned = cleaned.replace(/[^\wа-яА-ЯіїІЇ\dąćęłńóśźż\u0621-\u064A\u05D0-\u05EA\d]/g, '');
```
> This code will now also allow Arabic and Hebrew letters.

Could you test that regex in the console? You'd paste in this "clean" function
```js
function clean(str) {
  return str.replace(/[^\wа-яА-ЯіїІЇ\dąćęłńóśźż\u0621-\u064A\u05D0-\u05EA\d]/g, '');
}
```
and then run it to see if it works:
`clean('something'));`

It should return the same value you typed in if it worked. 

Or if you'd like you can paste in some example titles and I can test them myself when I get a chance.

**Comment by ShaleveHakime** [comment]
![image](https://github.com/theRealPadster/name-that-tune/assets/136990507/53bb5d31-2480-49a4-896f-2cd76f939698)
its removing the spaces for some reason

also here the name is the same but he doesn't reconize it
![Uploading image.png…]()

**Comment by theRealPadster** [comment]
It currently strips out spaces as part of the normalization, so that's intended. This way if, for example, a song had the word "meetup" in it, but someone typed "meet up", it would still match. 

The second part is a result of the built app code, not the test function you pasted into the console. Stuff in the console won't apply to the game. 

I've merged in that new regex, since it did seem to work when I pasted in your samples. Could you download the latest version from the dist branch and test it? If it works, I'll make a new release :)

**Comment by ShaleveHakime** [comment]
works! thank you so much!
